// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using framework_async_konzolos;
//
//    var dolgozo = Dolgozo.FromJson(jsonString);

namespace framework_async_konzolos
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Dolgozo
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("Aktiv")]
        public bool Aktiv { get; set; }

        [JsonProperty("Belepes")]
        public string Belepes { get; set; }

        [JsonProperty("Fizetes")]
        public long Fizetes { get; set; }

        [JsonProperty("Kilepes")]
        public string Kilepes { get; set; }

        [JsonProperty("Beosztas")]
        public string Beosztas { get; set; }

        [JsonProperty("Teljes_nev")]
        public string TeljesNev { get; set; }
        override public string ToString()
        {
            return $"ID: {Id}, Név: {TeljesNev}, Beosztás: {Beosztas}, Belépés: {Belepes}, Kilépés: {Kilepes ?? "N/A"}, Fizetés: {Fizetes}, Aktív: {Aktiv}";
        }
    }

    public partial class Dolgozo
    {
        public static Dolgozo[] FromJson(string json) => JsonConvert.DeserializeObject<Dolgozo[]>(json, framework_async_konzolos.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Dolgozo[] self) => JsonConvert.SerializeObject(self, framework_async_konzolos.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
 
}
