// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using async_konzolos_framework47;
//
//    var dolgozo = Dolgozo.FromJson(jsonString);

namespace async_konzolos_framework47
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Dolgozo
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("Aktiv")]
        public bool Aktiv { get; set; }

        [JsonProperty("Belepes")]
        public string Belepes { get; set; }

        [JsonProperty("Fizetes")]
        public long Fizetes { get; set; }

        [JsonProperty("Kilepes")]
        public string Kilepes { get; set; }

        [JsonProperty("Beosztas")]
        public string Beosztas { get; set; }

        [JsonProperty("Teljes_nev")]
        public string TeljesNev { get; set; }
    }

    public partial class Dolgozo
    {
        public static Dolgozo[] FromJson(string json) => JsonConvert.DeserializeObject<Dolgozo[]>(json, async_konzolos_framework47.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Dolgozo[] self) => JsonConvert.SerializeObject(self, async_konzolos_framework47.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
