// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using async_konzolos_framework47;
//
//    var dolgozo = Dolgozo.FromJson(jsonString);

namespace framework_WpfApp.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Data.SqlClient;
    using System.Globalization;
    using System.Runtime.CompilerServices;

    public partial class Dolgozo : INotifyPropertyChanged
    {
        private long _id;
        [JsonProperty("id")]
        public long Id
        {
            get => _id;
            set { _id = value; OnPropertyChanged(); }
        }

        private bool _aktiv;
        [JsonProperty("Aktiv")]
        public bool Aktiv
        {
            get => _aktiv;
            set { _aktiv = value; OnPropertyChanged(); }
        }

        private string _belepes;
        [JsonProperty("Belepes")]
        public string Belepes
        {
            get => _belepes;
            set { _belepes = value; OnPropertyChanged(); }
        }

        private long _fizetes;
        [JsonProperty("Fizetes")]
        public long Fizetes
        {
            get => _fizetes;
            set { _fizetes = value; OnPropertyChanged(); }
        }

        private string _kilepes;
        [JsonProperty("Kilepes")]
        public string Kilepes
        {
            get => _kilepes;
            set { _kilepes = value; OnPropertyChanged(); }
        }

        private string _beosztas;
        [JsonProperty("Beosztas")]
        public string Beosztas
        {
            get => _beosztas;
            set { _beosztas = value; OnPropertyChanged(); }
        }

        private string _teljesNev;
        [JsonProperty("Teljes_nev")]
        public string TeljesNev
        {
            get => _teljesNev;
            set { _teljesNev = value; OnPropertyChanged(); }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string name = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }
        private string _imageUrl;
        public string ImageUrl
        {
            get => _imageUrl;
            set { _imageUrl = value; OnPropertyChanged(); }
        }
        public DateTime? BelepesDate
        {
            get => DateTime.TryParse(Belepes, out var d) ? d : (DateTime?)null;
            set
            {
                Belepes = value?.ToString("yyyy-MM-dd");
                OnPropertyChanged();
            }
        }

        public DateTime? KilepesDate
        {
            get => DateTime.TryParse(Kilepes, out var d) ? d : (DateTime?)null;
            set
            {
                Kilepes = value?.ToString("yyyy-MM-dd");
                OnPropertyChanged();
            }
        }


        override public string ToString()
        {
            return $"ID: {Id}, Név: {TeljesNev}, Beosztás: {Beosztas}, Belépés: {Belepes}, Kilépés: {Kilepes ?? "N/A"}, Fizetés: {Fizetes}, Aktív: {Aktiv}";
        }
    }

    public partial class Dolgozo
    {
        public static Dolgozo[] FromJson(string json) => JsonConvert.DeserializeObject<Dolgozo[]>(json, framework_WpfApp.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Dolgozo[] self) => JsonConvert.SerializeObject(self, framework_WpfApp.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
